name: Python Build

on:
  push

jobs:
  Install-Test:
    name: Installation test for python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y swig bash mingw-w64
      - name: Install dependencies for macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install swig mingw-w64 bash
      - name: Install dependencies for windows
        if: matrix.os == 'windows-latest'
        run: |
          pip install setuptools wheel twine
          pip install numpy sklearn scipy
          choco install swig mingw git
      - name: Install abess
        run: |
          cd ./python
          python setup.py bdist_wheel
          cd dist
          pip install abess-0.4.0-cp38-cp38-win_amd64.whl
          cd ..
          cd ..
          python mytest.py
