name: Python Build

on:
  push

jobs:
  Install-Test:
    name: Installation test for python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        python-version: [3.6]
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y swig bash mingw-w64
      - name: Install dependencies for macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install swig mingw-w64 bash
      - name: Install dependencies for windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install swig mingw git
      - name: Install abess
        run: |
          pip install numpy
          cd ./python
          ls
          python setup.py install
          ls
          cd ..
          python mytest.py
